/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.imbochfckyeahprojects.finalproject;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.LinkedList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author imbochfuckyeah
 */
public class loadusers extends javax.swing.JFrame {
    
    /**
     * Creates new form loadusers
     */
    public loadusers() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /*Este codigo es para hacer commit*/
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        divclass = new javax.swing.JPanel();
        jtitle = new javax.swing.JLabel();
        jsubtitle = new javax.swing.JLabel();
        jbackmenu = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        datausers = new javax.swing.JTable();
        btload = new javax.swing.JButton();
        btsave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(0, 153, 204));
        background.setForeground(new java.awt.Color(0, 153, 204));

        divclass.setBackground(new java.awt.Color(255, 255, 255));

        jtitle.setFont(new java.awt.Font("Montserrat", 1, 36)); // NOI18N
        jtitle.setForeground(new java.awt.Color(102, 102, 102));
        jtitle.setText("Load users");

        jsubtitle.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N
        jsubtitle.setForeground(new java.awt.Color(0, 153, 204));
        jsubtitle.setText("Here you can check all the data about the users.");

        jbackmenu.setFont(new java.awt.Font("Comfortaa", 0, 10)); // NOI18N
        jbackmenu.setForeground(new java.awt.Color(102, 102, 102));
        jbackmenu.setText("Back to menu");
        jbackmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbackmenuMouseClicked(evt);
            }
        });

        datausers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(datausers);

        btload.setBackground(new java.awt.Color(0, 153, 204));
        btload.setFont(new java.awt.Font("Montserrat", 1, 15)); // NOI18N
        btload.setForeground(new java.awt.Color(255, 255, 255));
        btload.setText("Load file");
        btload.setBorder(null);
        btload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btloadActionPerformed(evt);
            }
        });

        btsave.setBackground(new java.awt.Color(0, 153, 204));
        btsave.setFont(new java.awt.Font("Montserrat", 1, 15)); // NOI18N
        btsave.setForeground(new java.awt.Color(255, 255, 255));
        btsave.setText("Save users");
        btsave.setBorder(null);
        btsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout divclassLayout = new javax.swing.GroupLayout(divclass);
        divclass.setLayout(divclassLayout);
        divclassLayout.setHorizontalGroup(
            divclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(divclassLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(divclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
                    .addGroup(divclassLayout.createSequentialGroup()
                        .addComponent(jtitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbackmenu))
                    .addGroup(divclassLayout.createSequentialGroup()
                        .addComponent(jsubtitle)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(divclassLayout.createSequentialGroup()
                        .addComponent(btload, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btsave, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        divclassLayout.setVerticalGroup(
            divclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, divclassLayout.createSequentialGroup()
                .addGroup(divclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(divclassLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(divclassLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbackmenu)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsubtitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(divclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btload, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btsave, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(divclass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(divclass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbackmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbackmenuMouseClicked
        // TODO add your handling code here:
        menu m = new menu();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbackmenuMouseClicked

    private void btloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btloadActionPerformed
        // TODO add your handling code here:
        JFileChooser selectfile = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Files csv", "csv");
        
        selectfile.setFileFilter(filter);
        
        int select = selectfile.showOpenDialog(this);
        
        if(select == JFileChooser.APPROVE_OPTION){
            File file = selectfile.getSelectedFile();
            loadfile(file);
        }else{
            JOptionPane.showMessageDialog(this, "File extension error!, try again.");
        }
    }//GEN-LAST:event_btloadActionPerformed

    private void btsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btsaveActionPerformed

    public void loadfile(File file){
        FileReader fr = null;
        BufferedReader br = null;
        try{
            fr = new FileReader(file);
            br = new BufferedReader(fr);
            
            String line;
            while((line = br.readLine())!=null){
                String arreglo [] = line.split(",");
                if(arreglo.length==6){
                    newusers user = new newusers();
                    user.setName(arreglo[0]);
                    user.setLastname(arreglo[1]);
                    user.setEmail(arreglo[2]);
                    user.setUser(arreglo[3]);
                    user.setPassword(arreglo[4]);
                    user.setRol(arreglo[5]);
                    masterclass.users.add(user);
                }
            }
            setdatatable();
        }catch (Exception ex){
            ex.printStackTrace();
        }finally{
            try{
                if(fr != null){
                    fr.close();
                }
            }catch(Exception ex){
                ex.printStackTrace();
            }
        }
    }
    
    private void setdatatable(){

            DefaultTableModel data = new DefaultTableModel(new String[]{"Name", "Lastname", "Email", "User", "Password", "Rol"}, masterclass.users.size());
            datausers.setModel(data);

            TableModel model = datausers.getModel();

            for (int i = 0; i < masterclass.users.size(); i++) {
                newusers datau = masterclass.users.get(i);
                model.setValueAt(datau.getName(), i, 0);
                model.setValueAt(datau.getLastname(), i, 1);
                model.setValueAt(datau.getEmail(), i, 2);
                model.setValueAt(datau.getUser(), i, 3);
                model.setValueAt(datau.getPassword(), i, 4);
                model.setValueAt(datau.getRol(), i, 5);
            }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btload;
    private javax.swing.JButton btsave;
    private javax.swing.JTable datausers;
    private javax.swing.JPanel divclass;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jbackmenu;
    private javax.swing.JLabel jsubtitle;
    private javax.swing.JLabel jtitle;
    // End of variables declaration//GEN-END:variables
}
